print("Enter How many Student You Want to Register")
times=int(input("Enter Total register Number: "))
for x in range(times):
    print("----------------------------------------")
    Name=str(input("Enter Sname: "))
    RollNo=int(input("Enter Srollno: "))
    Gender=str(input("Enter Gender: "))
    BloodGroup=str(input("Enter Blood Group: "))
    DataOFBirth=str(input("Enter Date Of Birth: "))
    print("-----Student DataBase------")
    print("---------------------------")
    print("Name:",Name)
    print("RollNo:",RollNo)
    print("Gender:",Gender)
    print("BloodGroup:",BloodGroup)
    print("DataOFBirth:",DataOFBirth)
    print(f"{x+1} Student Register Sucess ")
    print("--------------------------")
